name: DL CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch pytest black ruff

      # 4️⃣ Linting
      - name: Lint code
        run: |
          black --check .
          ruff check .

      # 5️⃣ Mini entraînement pour vérifier que ça fonctionne
      - name: Run training script
        run: python hello.py  # remplace par le nom de ton fichier
